services:
  - type: web
    name: ostrich-customer-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DB_HOST
        fromService:
          type: pserv
          name: mysql-ostrich-tviazone-5922.i.aivencloud.com
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: defaultdb
      - key: DB_PORT
        value: "16599"