services:
  - type: web
    name: ostrich-customer-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: SECRET_KEY
        value: customer-secret-key-production
      - key: DB_HOST
        value: mysql-ostrich-tviazone-5922.i.aivencloud.com
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        generateValue: true
      - key: DB_NAME
        value: defaultdb
      - key: DB_PORT
        value: 16599